version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:11 
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: Install Dependecies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: Generate Artifacts
          command: "npm run electron:build"
      - store_artifacts:
          path: ~/out


          
